# file: .github/workflows/home.yml
name: home
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - name: setup
        uses: actions/checkout@v4
        run: make setup
          -
      - name: test
        uses: actions/checkout@v4
        run: make test

      - name: link
        uses: actions/checkout@v4
        run: make link
